### ISSUE TITLE
UUID without -

### ISSUE THREAD

**Issue by arnulfojr** [olistic/graphql-type-uuid#1]
What do you think if this library can support UUID formats without the `-` separator?

Reasoning: UUIDs are usually sent as strings but the underlying implementation is based on bits... making the `-` just a representation aid for the human eye.

**Comment by olistic** [comment]
The hyphens are part of the [RFC spec](https://tools.ietf.org/html/rfc4122), in which the library is based:

```
The formal definition of the UUID string representation is
provided by the following ABNF [7]:

UUID = time-low "-" time-mid "-"
       time-high-and-version "-"
       clock-seq-and-reserved
       clock-seq-low "-" node
```

This library will validate the UUID according to what's specified there, strictly, as that was one of the main reasons for its existence.
