### ISSUE TITLE
Imports don't work in TypeScript

### ISSUE THREAD

**Issue by moltar** [olistic/graphql-type-uuid#2]
Need to do it the following way to make them work:

```
import * as GraphQLUUID from 'graphql-type-uuid';
```

I'm using NestJS's default TS config. Not really sure what the problem is. Just reporting, in case it can be fixed and in case someone else stumbles on this :)

**Comment by ddehghan** [comment]
try:

import GraphQLUUID from 'graphql-type-uuid';

**Comment by olistic** [comment]
@moltar were you able to make it work using the regular `import GraphQLUUID from 'graphql-type-uuid'` form?

**Comment by olistic** [comment]
Please re-open if this is still an issue.
