### ISSUE TITLE
Valid UUID does not match 

### ISSUE THREAD

**Issue by davidecalignano** [olistic/graphql-type-uuid#3]
I just found a valid UUID (`02c44232-4ac6-6eda-9ad2-735096bbaf34`) that does not pass the validation. Could you please have a look?

**Comment by olistic** [comment]
Hey @davidecalignano. The provided UUID (`02c44232-4ac6-6eda-9ad2-735096bbaf34`) is not valid according to the specification in [RFC 4122](https://tools.ietf.org/html/rfc4122), which this project follows. I just added a mention to that in the README, which I was missing.

In particular, the `6` in the third block (`6eda`) must be a number from 1 to 5, representing any of the valid five versions of UUID according to the RFC.
